### ISSUE TITLE
The current version published on Pypi does not contains the fix for devpi-server 6.x.x

### ISSUE THREAD

**Issue by gabrielboucher** [devpi/devpi-passwd-reset#1]
I did spend several hours debugging the plugin to see why it wouldn't load on latest devpi-server, just to end up realizing the latest version has not been published on PyPi yet. 

Please publish the latest version or at least keep this issue active until it is so that the next person won't waste so much time on this issue.

Thanks!

**Comment by fschulze** [comment]
@gabrielboucher sorry about that, I hope you learned new stuff during debugging, so it wasn't a total waste. GitHub turns of scheduled tests after a while of inactivity, that is why I initially didn't notice. All plugins are now tested in the devpi repository itself.
